### ISSUE TITLE
[front] Cards 컴포넌트 margin-right 수정 요청

### ISSUE THREAD

**Issue by seuyu42** [42DoProject/42DoProject#24]
Cards 컴포넌트를 활용하여 그리드뷰 페이지를 만드는 과정에서 Cards에 적용된 1.7rem의 우측마진으로 인해 간격수정이 어렵습니다.

**Comment by Jiyong95** [comment]
(AllProjectPage.js)
   <div className="allproject__wrap">
        <ProjectTypeBar />
        <ProjectContents />
      </div>

(AllProjectPage.scss)
.allproject__wrap {
  margin: 0 auto;
  max-width: 1440px;
}

이 방법을 통해 화면 크기에 따라 간격이 넓어지는 것을 해결하였습니다.
그리고 모든 페이지에  max-width:1440px로 규격을 맞추자는 서영님의 의견이 있어서 
다음과 같이 margin : 0 auto; -> 화면 크기에 따라 양쪽 마진이 똑같이 적용되며 가운데 정렬되는 기능과
max-width:1440px;  요소의 최대 크기를 1440px로 고정하는 기능을 추가해야합니다!
