### ISSUE TITLE
[front?, back?] 진행 중인 프로젝트

### ISSUE THREAD

**Issue by Yechan0815** [42DoProject/42DoProject#339]
![a](https://user-images.githubusercontent.com/12230655/139525234-bcb7903b-7c9d-4503-96a9-7c38a2bdbc98.PNG)
진행 중인 프로젝트가 하나 있지만 0개로 나옵니다.

(혹시 제가 잘못 이해해서 올라왔거나 아직 작업이 안 된 부분이면 그냥 close 해주시면 됩니다)

**Comment by Yechan0815** [comment]
![a](https://user-images.githubusercontent.com/12230655/139525386-0f3ecfc6-4c84-44af-b942-daaac91f0802.PNG)
애초에 모집중으로 나옵니다

**Comment by Yechan0815** [comment]
![a](https://user-images.githubusercontent.com/12230655/139525394-329d9e06-d6d7-41a8-a705-66a315ce7e52.PNG)
새 프로젝트를 만들 경우 진행 중으로 잘 바뀌었습니다

**Comment by Kitkat-42** [comment]
이부분은 데이터가 이미 올라간 상태에서 수정사항이 반영되어 그렇습니다!
