### ISSUE TITLE
[front] 유효하지 않은 url 처리

### ISSUE THREAD

**Issue by Yechan0815** [42DoProject/42DoProject#371]
![a](https://user-images.githubusercontent.com/12230655/139645863-12dc85b4-6119-4f80-9461-4f9ccf06e513.PNG)
유효하지 않은 url에 접근했을 때 이렇게 빈 화면에 머물게 되는데, 특정한 행동이 취해졌으면 좋겠습니다

**Comment by Jiyong95** [comment]
해결완료했고 merge하고 issue 닫겠습니당
