### ISSUE TITLE
[back] blur image 섞임

### ISSUE THREAD

**Issue by seoysauce** [42DoProject/42DoProject#544]
![DD56ADFE-A8DB-4BB9-8045-FC9742BB0525](https://user-images.githubusercontent.com/65898861/142719000-5920888c-e546-468c-ba14-788f595b163e.png)

수정 후에도 여전히 블러 이미지가 섞이는 문제가 있습니다

**Comment by Yechan0815** [comment]
작업 브랜치에 main이 머지된 상태에서 일어난 건가요?

**Comment by seoysauce** [comment]
배포된 페이지에서 일어납니다!
