### ISSUE TITLE
[front? back?] 피드

### ISSUE THREAD

**Issue by Yechan0815** [42DoProject/42DoProject#643]
![a](https://user-images.githubusercontent.com/12230655/143671137-6c0e97c1-bd8a-4255-b1f4-a98c875ba791.PNG)

프로젝트 피드가 제대로 보이지 않습니다

**Comment by seoysauce** [comment]
![스크린샷 2021-11-27 오후 4 06 37](https://user-images.githubusercontent.com/65898861/143671882-037989e9-71d8-4f91-ba9d-b057d6e3ad92.png)

흠 저는 잘 되는 것 같은데 어떤 경우에 안되는건가요?

**Comment by Yechan0815** [comment]
음... 저는 지금 다시 해봐도 안되네요.. 계속 똑같이 뜹니ㅣ다

**Comment by Yechan0815** [comment]
백에서 넘겨줄 때부터 undefined로 넘어오네요

**Comment by Daewoong-Jeon** [comment]
오류 수정했습니다!
확인 부탁드립니다.
