### ISSUE TITLE
[front] 진행중 프로젝트에 지원 가능한 오류

### ISSUE THREAD

**Issue by Daewoong-Jeon** [42DoProject/42DoProject#847]
![스크린샷 2022-01-09 오후 9 44 32](https://user-images.githubusercontent.com/59330163/148682687-eebec3f8-05f4-4c8e-92a7-eaeca11c0b4b.png)
프로젝트가 진행중으로 바뀌어도 +버튼이 지워지지 않습니다.

**Comment by seoysauce** [comment]
원래 진행중이어도 지원가능한걸로 압니다!

**Comment by Daewoong-Jeon** [comment]
> 원래 진행중이어도 지원가능한걸로 압니다! (진행중이어도 지속적으로 모집가능하게 하기 위해)

아하 의도하신거라면 이슈 닫겠습니다
