### ISSUE TITLE
포지션 선택 오류

### ISSUE THREAD

**Issue by sanvit** [42DoProject/42DoProject#849]
포지션 선택시 선택한 포지션이 아닌 다른 포지션으로 신청이 됩니다.

https://sharex.scdn.pw/2022/01/42do-project-selection-error.mp4

**Comment by Daewoong-Jeon** [comment]
> 포지션 선택시 선택한 포지션이 아닌 다른 포지션으로 신청이 됩니다.
> 
> https://sharex.scdn.pw/2022/01/42do-project-selection-error.mp4

소중한 이슈 감사합니다 :)

**Comment by seuyu42** [comment]
포지션 신청 기능에 모달을 추가하면서 에러가 발생했습니다.

모달을 열게하는 flag를 true, false로 두고 모달창을 뜨게했는데 이 부분이 모든 신청버튼을 같이 인식하게되어버렸습니다.
